version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DATABASE_PATH=/app/data/agriculture_monitor.db
      - PYTHONPATH=/app
      - FARM_LATITUDE=40.7128
      - FARM_LONGITUDE=-74.0060
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  backend_data:
    driver: local

networks:
  default:
    name: agri-monitor-network