services:
  - type: web
    name: smart-agriculture-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: backend
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: FARM_LATITUDE
        value: 13.353599
      - key: FARM_LONGITUDE
        value: 74.793633

  - type: web
    name: smart-agriculture-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: smart-agriculture-backend
          property: host
