services:
  # Backend API service
  - type: web
    name: agri-monitor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_PATH
        value: ./agriculture_monitor.db
      - key: OPENWEATHER_API_KEY
        sync: false  # Set this in Render dashboard
      - key: FARM_LATITUDE
        value: "40.7128"
      - key: FARM_LONGITUDE  
        value: "-74.0060"
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health

  # Frontend static site
  - type: web
    name: agri-monitor-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: agri-monitor-api
          property: host

databases:
  # Optional: PostgreSQL for production (uncomment if needed)
  # - name: agri-monitor-db
  #   databaseName: agriculture_monitor
  #   user: agri_user