# render.yaml - Backend only (Frontend deployed separately as Static Site)
services:
  - type: web
    name: smart-agriculture-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: backend
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/agriculture_monitor.db
      - key: FARM_LATITUDE
        value: 13.353599
      - key: FARM_LONGITUDE
        value: 74.793633

# Note: Frontend must be deployed separately as a Static Site
# because Render doesn't support "static" type in render.yaml
# Use manual deployment for frontend:
# 1. Go to Render Dashboard
# 2. Click "New +" -> "Static Site"
# 3. Root Directory: frontend
# 4. Publish Directory: public
